// Generated by devkit/scripts/generate.mts from the Breakreach OpenAPI spec. Do not edit.
// API version 1.1.0

import { Core, type RequestOptions } from "./core";

/** A JSON object whose fields the spec doesn't list yet */
export type JsonObject = { [key: string]: any };

export interface Post {
  id: string;
  content: string;
  status: "draft" | "scheduled" | "publishing" | "published" | "failed";
  scheduledAt: string;
  accountIds: string[];
  media: string[];
  metrics: {
    views?: number;
    likes?: number;
    comments?: number;
    shares?: number;
  } | null;
  /**
   * Human-readable failure reason when status is failed
   */
  error: string | null;
}

export interface Account {
  id: string;
  platform: "instagram" | "tiktok" | "x" | "reddit" | "linkedin" | "youtube" | "facebook" | "threads" | "bluesky" | "pinterest" | "telegram" | "discord" | "slack" | "mastodon" | "wordpress";
  displayName: string;
  /**
   * Present when the account's authorization has expired, was revoked on the network's side, or expires soon (LinkedIn lasts about 60 days): the user must reconnect it in Breakreach settings
   */
  warning?: string;
}

export interface Workspace {
  slug: string;
  name: string;
  timezone: string;
}

export interface CreatedPost {
  id: string;
  /**
   * publishing when publishNow was set, draft when draft was set
   */
  status: "draft" | "scheduled" | "publishing";
  /**
   * Publish time, in UTC
   */
  scheduledAt: string;
  /**
   * Target accounts as "platform (display name)", e.g. "instagram (Acme)"
   */
  accounts: string[];
}

export interface ConnectLink {
  id: string;
  /**
   * The page to send, only returned at creation
   */
  url?: string;
  /**
   * Workspace slug
   */
  workspace: string;
  platforms: string[];
  redirectUrl: string | null;
  expiresAt: string;
  status: "active" | "expired" | "revoked";
  connected: Array<{
    accountId: string;
    platform: string;
    displayName: string;
    connectedAt: string;
  }>;
}

export interface CommentDmRule {
  id: string;
  accountId: string;
  platform: "instagram" | "facebook";
  account?: {
    displayName?: string;
    avatarUrl?: string | null;
  };
  /**
   * The Instagram or Facebook post the rule watches; null = every post of the account
   */
  mediaId: string | null;
  media: {
    caption?: string;
    thumbnailUrl?: string | null;
    permalink?: string | null;
    timestamp?: string | null;
  } | null;
  /**
   * Empty = every comment triggers the rule
   */
  keywords: string[];
  match: "contains" | "exact";
  dmText: string;
  publicReplies: string[];
  active: boolean;
  stats: {
    triggered?: number;
    sent?: number;
    failed?: number;
  };
  lastTriggeredAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CommentDmRuleInput {
  /**
   * Instagram account or Facebook Page id from /v1/accounts (create only, a rule can't change account)
   */
  accountId?: string;
  /**
   * Instagram or Facebook post id to watch (from /v1/comment-dm-rules/media or the postId of /v1/comments). Omit or null for every post
   */
  mediaId?: string | null;
  /**
   * Instead of mediaId: a Breakreach post id published on this account
   */
  postId?: string;
  /**
   * Words or phrases that trigger the DM, case and accents ignored. Empty = every comment
   */
  keywords?: string[];
  /**
   * contains = the keyword appears as a whole word or phrase; exact = the comment is just the keyword (punctuation and emoji around it ignored)
   */
  match?: "contains" | "exact";
  /**
   * The DM sent to the commenter, links allowed. {username} becomes their @handle on Instagram, their first name on Facebook. Required on create
   */
  dmText?: string;
  /**
   * Optional public replies under the comment once the DM is sent, one picked at random. {username} becomes their @handle on Instagram, their first name on Facebook
   */
  publicReplies?: string[];
  active?: boolean;
  workspace?: string;
}

export interface CommentDmEvent {
  id: string;
  ruleId: string;
  status: "pending" | "sent" | "failed" | "skipped";
  /**
   * Why it was skipped: duplicate (the person already got this rule's DM), too_old (Instagram allows private replies within 7 days), plan (no active plan), paused, deleted
   */
  reason: string | null;
  error: string | null;
  commentId: string;
  commentText: string;
  /**
   * Instagram handle
   */
  commenterUsername: string | null;
  /**
   * Facebook name
   */
  commenterName: string | null;
  mediaId: string | null;
  dmMessageId: string | null;
  /**
   * The public reply posted under the comment
   */
  publicReply: string | null;
  publicReplyError: string | null;
  createdAt: string;
  sentAt: string | null;
}

export interface DmTrigger {
  /**
   * keyword = a DM containing a keyword; any_message = any DM (welcome or away reply); story_mention = someone mentions the account in their story (Instagram); story_reply = a reply to one of its stories, optionally with keywords (Instagram); ref = someone opens ig.me/m/<username>?ref=<ref> or m.me/<page id>?ref=<ref> and writes
   */
  type: "keyword" | "any_message" | "story_mention" | "story_reply" | "ref";
  /**
   * keyword (required) and story_reply (optional); case and accents ignored
   */
  keywords?: string[];
  match?: "contains" | "exact";
  ref?: string | null;
}

/**
 * One step of a flow. A message with choices, a condition and a handoff must be the last step of their list; what follows goes inside their branches. Up to 40 steps, branches 6 levels deep.
 */
export interface DmStep {
  /**
   * Kept across edits so people in the flow carry on; generated when omitted
   */
  id?: string;
  type: "message" | "wait" | "condition" | "handoff";
  /**
   * message: up to 1000 bytes (640 characters with a button). {username} = their @handle on Instagram, first name on Messenger; {first_name}
   */
  text?: string;
  /**
   * message: a link button; clicks are counted (the link goes through api.breakreach.com/l/...)
   */
  button?: {
    title?: string;
    url?: string;
  } | null;
  /**
   * message: quick-reply choices, each with its own steps. Not with a button
   */
  choices?: Array<{
    id?: string;
    label?: string;
    steps?: DmStep[];
  }>;
  /**
   * message with choices: a typed answer that isn't a choice, or no answer within afterMinutes
   */
  otherwise?: {
    afterMinutes?: number;
    steps?: DmStep[];
  } | null;
  /**
   * wait
   */
  minutes?: number;
  /**
   * condition: a reply, a reply containing keywords, a click on an earlier link button (each waited for up to withinMinutes), or whether they follow the account (Instagram, checked at once)
   */
  check?: "replied" | "keyword" | "clicked" | "follows";
  keywords?: string[];
  match?: "contains" | "exact";
  withinMinutes?: number;
  yes?: DmStep[];
  no?: DmStep[];
  /**
   * handoff: shown in the Inbox
   */
  note?: string;
}

export interface DmAutomation {
  id?: string;
  accountId?: string;
  platform?: "instagram" | "facebook";
  account?: {
    displayName?: string;
    avatarUrl?: string | null;
  };
  name?: string;
  trigger?: DmTrigger;
  /**
   * For a ref trigger: the link to share (link in bio, QR code, ad)
   */
  refLink?: string | null;
  steps?: DmStep[];
  reentry?: "once" | "always";
  cooldownHours?: number;
  active?: boolean;
  stats?: {
    started?: number;
    completed?: number;
    handedOff?: number;
    clicks?: number;
    failed?: number;
  };
  lastTriggeredAt?: string | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface DmAutomationInput {
  /**
   * Instagram account or Facebook Page id from /v1/accounts (create only)
   */
  accountId?: string;
  name?: string;
  trigger?: DmTrigger;
  /**
   * Required on create. On update, the whole list
   */
  steps?: DmStep[];
  /**
   * once = a person goes through it once; always = each time they trigger it, at most once per cooldownHours
   */
  reentry?: "once" | "always";
  cooldownHours?: number;
  active?: boolean;
  workspace?: string;
}

export interface DmAutomationRun {
  id?: string;
  automationId?: string;
  status?: "running" | "waiting" | "completed" | "handed_off" | "stopped" | "window_closed" | "failed";
  contact?: {
    /**
     * Instagram-scoped or Page-scoped id
     */
    id?: string;
    username?: string | null;
    name?: string | null;
  };
  trigger?: {
    type?: string;
    text?: string | null;
    ref?: string | null;
  };
  stepId?: string | null;
  waiting?: {
    kind?: "timer" | "choice" | "reply" | "click";
    stepId?: string;
    until?: string;
  } | null;
  clicks?: number;
  log?: Array<{
    at?: string;
    /**
     * trigger, sent, choice, reply, click, branch, wait, waited, handoff, end, error
     */
    kind?: string;
    stepId?: string | null;
    text?: string | null;
    detail?: string | null;
  }>;
  /**
   * done, handoff, human_replied (someone answered by hand), window (Meta's 24-hour window closed), paused, deleted, flow_changed, stopped_by_team, send, account
   */
  endReason?: string | null;
  error?: string | null;
  createdAt?: string;
  endedAt?: string | null;
}

export interface Error {
  /**
   * Human-readable reason
   */
  error: string;
}

/**
 * Response of uploadMediaFile
 */
export interface UploadMediaFileResponse {
  url: string;
}

/**
 * Response of listWorkspaces
 */
export interface ListWorkspacesResponse {
  workspaces: Workspace[];
}

/**
 * Body of createWorkspace
 */
export interface CreateWorkspaceBody {
  /**
   * Up to 80 characters
   */
  name: string;
  /**
   * IANA timezone used to read scheduledAt, e.g. Europe/Paris (default UTC)
   */
  timezone?: string;
}

/**
 * Response of createWorkspace
 */
export interface CreateWorkspaceResponse {
  workspace: Workspace;
}

/**
 * Body of createConnectLink
 */
export interface CreateConnectLinkBody {
  /**
   * Workspace slug (optional, defaults to your first workspace)
   */
  workspace?: string;
  /**
   * Networks offered on the page (default: all)
   */
  platforms?: Array<"instagram" | "facebook" | "threads" | "tiktok" | "linkedin" | "youtube" | "x" | "pinterest" | "bluesky" | "reddit" | "telegram" | "discord" | "slack" | "mastodon" | "wordpress">;
  /**
   * Where the Done button sends them: https, or http on localhost
   */
  redirectUrl?: string;
  /**
   * How long the link works (default 24)
   */
  expiresInHours?: number;
}

/**
 * Response of createConnectLink
 */
export interface CreateConnectLinkResponse {
  connectLink: ConnectLink;
}

/**
 * Response of getConnectLink
 */
export interface GetConnectLinkResponse {
  connectLink: ConnectLink;
}

/**
 * Response of revokeConnectLink
 */
export interface RevokeConnectLinkResponse {
  connectLink: ConnectLink;
}

/**
 * Query parameters of listAccounts
 */
export interface ListAccountsQuery {
  /**
   * Workspace slug (defaults to your first workspace)
   */
  workspace?: string;
}

/**
 * Response of listAccounts
 */
export interface ListAccountsResponse {
  accounts: Account[];
  /**
   * Present only when no account is connected: explains how to connect one, with the link to the workspace settings
   */
  message?: string;
}

/**
 * Query parameters of listPosts
 */
export interface ListPostsQuery {
  workspace?: string;
  status?: "draft" | "scheduled" | "published" | "failed" | "all";
  limit?: number;
}

/**
 * Response of listPosts
 */
export interface ListPostsResponse {
  posts: Post[];
}

/**
 * Body of createPost
 */
export interface CreatePostBody {
  /**
   * The post text. For Reddit, the first line becomes the title.
   */
  content: string;
  /**
   * Target account ids from GET /v1/accounts
   */
  accountIds: string[];
  /**
   * ISO datetime in the workspace timezone, e.g. 2026-09-20T11:00:00
   */
  scheduledAt?: string;
  publishNow?: boolean;
  useNextSlot?: boolean;
  /**
   * Save as a draft for review instead of scheduling it. Can't be combined with publishNow
   */
  draft?: boolean;
  media?: string[];
  /**
   * Workspace slug (optional)
   */
  workspace?: string;
  /**
   * Required when targeting Pinterest — see GET /v1/pinterest-boards
   */
  pinterestBoardId?: string;
  /**
   * Destination URL of the pin (optional, http(s), up to 2,048 characters). The pin title is the first line of content
   */
  pinterestLink?: string;
  /**
   * Subreddit without r/ — defaults to the user profile
   */
  redditSubreddit?: string;
  /**
   * Post flair name when the subreddit requires one
   */
  redditFlairText?: string;
  tiktokSettings?: {
    privacyLevel?: "PUBLIC_TO_EVERYONE" | "MUTUAL_FOLLOW_FRIENDS" | "FOLLOWER_OF_CREATOR" | "SELF_ONLY";
    disableComment?: boolean;
    disableDuet?: boolean;
    disableStitch?: boolean;
  };
}

/**
 * Response of createPost
 */
export interface CreatePostResponse {
  post: CreatedPost;
}

/**
 * Body of updatePost
 */
export interface UpdatePostBody {
  content?: string;
  /**
   * Replaces the target accounts
   */
  accountIds?: string[];
  /**
   * Replaces the media
   */
  media?: string[];
  /**
   * ISO datetime in the workspace timezone, e.g. 2026-09-20T11:00:00
   */
  scheduledAt?: string;
  publishNow?: boolean;
  useNextSlot?: boolean;
  /**
   * true moves the post back to drafts
   */
  draft?: boolean;
  /**
   * Workspace slug (optional)
   */
  workspace?: string;
  pinterestBoardId?: string;
  pinterestLink?: string;
  redditSubreddit?: string;
  redditFlairText?: string;
}

/**
 * Response of updatePost
 */
export interface UpdatePostResponse {
  post: CreatedPost;
}

/**
 * Query parameters of deletePost
 */
export interface DeletePostQuery {
  workspace?: string;
}

/**
 * Response of deletePost
 */
export interface DeletePostResponse {
  ok: boolean;
}

/**
 * Body of uploadMedia
 */
export interface UploadMediaBody {
  url: string;
}

/**
 * Response of uploadMedia
 */
export interface UploadMediaResponse {
  url: string;
}

/**
 * Query parameters of getNextSlot
 */
export interface GetNextSlotQuery {
  workspace?: string;
}

/**
 * Response of getNextSlot
 */
export interface GetNextSlotResponse {
  /**
   * Local time in the workspace timezone, to pass as scheduledAt
   */
  scheduledAt: string;
  timezone: string;
  utc: string;
}

/**
 * Query parameters of listPinterestBoards
 */
export interface ListPinterestBoardsQuery {
  workspace?: string;
}

/**
 * Response of listPinterestBoards
 */
export interface ListPinterestBoardsResponse {
  accountId: string;
  boards: Array<{
    id: string;
    name: string;
  }>;
}

/**
 * Query parameters of getAnalytics
 */
export interface GetAnalyticsQuery {
  workspace?: string;
}

/**
 * Response of getAnalytics
 */
export interface GetAnalyticsResponse {
  totals: {
    views: number;
    likes: number;
    comments: number;
    shares: number;
    posts: number;
  };
  topPosts: Array<{
    id: string;
    content: string;
    metrics: {
      views?: number;
      likes?: number;
      comments?: number;
      shares?: number;
    } | null;
  }>;
}

/**
 * Query parameters of getAccountStats
 */
export interface GetAccountStatsQuery {
  workspace?: string;
}

/**
 * Query parameters of getPostInsights
 */
export interface GetPostInsightsQuery {
  accountId: string;
  /**
   * Platform post id
   */
  postId: string;
  workspace?: string;
}

/**
 * Query parameters of getAccountTrends
 */
export interface GetAccountTrendsQuery {
  days?: number;
  accountId?: string;
  refresh?: boolean;
  workspace?: string;
}

/**
 * Query parameters of getPostMetrics
 */
export interface GetPostMetricsQuery {
  /**
   * Fetch fresh metrics from the platforms before answering, instead of the last stored ones
   */
  refresh?: boolean;
  workspace?: string;
}

/**
 * Response of getPostMetrics
 */
export interface GetPostMetricsResponse {
  id: string;
  status: string;
  publishedAt: string | null;
  metrics: {
    views?: number;
    likes?: number;
    comments?: number;
    shares?: number;
  } | null;
  perPlatform: Array<{
    accountId: string;
    platform: string;
    platformPostId: string;
  }>;
  error: string | null;
}

/**
 * Query parameters of getPostComments
 */
export interface GetPostCommentsQuery {
  workspace?: string;
}

/**
 * Query parameters of listRecentComments
 */
export interface ListRecentCommentsQuery {
  platform?: "instagram" | "facebook" | "threads" | "x";
  accountId?: string;
  workspace?: string;
}

/**
 * Body of replyToComment
 */
export interface ReplyToCommentBody {
  accountId: string;
  platform: "instagram" | "facebook" | "threads" | "x";
  commentId: string;
  message: string;
  workspace?: string;
}

/**
 * Query parameters of getContentPerformance
 */
export interface GetContentPerformanceQuery {
  days?: number;
  platform?: string;
  accountId?: string;
  sortBy?: "date" | "views" | "likes" | "comments" | "shares" | "engagement";
  limit?: number;
  /**
   * Rebuild from the platforms instead of the cache
   */
  refresh?: boolean;
  workspace?: string;
}

/**
 * Query parameters of listConversations
 */
export interface ListConversationsQuery {
  platform?: "facebook" | "instagram" | "x";
  accountId?: string;
  workspace?: string;
}

/**
 * Query parameters of getConversationMessages
 */
export interface GetConversationMessagesQuery {
  accountId: string;
  participantId?: string;
  workspace?: string;
}

/**
 * Body of sendDirectMessage
 */
export interface SendDirectMessageBody {
  accountId: string;
  message: string;
  participantId?: string;
  workspace?: string;
}

/**
 * Query parameters of listCommentDmRules
 */
export interface ListCommentDmRulesQuery {
  accountId?: string;
  mediaId?: string;
  workspace?: string;
}

/**
 * Response of listCommentDmRules
 */
export interface ListCommentDmRulesResponse {
  rules: CommentDmRule[];
}

/**
 * Response of createCommentDmRule
 */
export interface CreateCommentDmRuleResponse {
  rule: CommentDmRule;
}

/**
 * Query parameters of listCommentDmMedia
 */
export interface ListCommentDmMediaQuery {
  accountId: string;
  limit?: number;
  workspace?: string;
}

/**
 * Response of updateCommentDmRule
 */
export interface UpdateCommentDmRuleResponse {
  rule: CommentDmRule;
}

/**
 * Query parameters of deleteCommentDmRule
 */
export interface DeleteCommentDmRuleQuery {
  workspace?: string;
}

/**
 * Query parameters of listCommentDmEvents
 */
export interface ListCommentDmEventsQuery {
  limit?: number;
  workspace?: string;
}

/**
 * Response of listCommentDmEvents
 */
export interface ListCommentDmEventsResponse {
  events: CommentDmEvent[];
}

/**
 * Query parameters of listDmAutomations
 */
export interface ListDmAutomationsQuery {
  accountId?: string;
  workspace?: string;
}

/**
 * Response of listDmAutomations
 */
export interface ListDmAutomationsResponse {
  automations?: DmAutomation[];
}

/**
 * Response of createDmAutomation
 */
export interface CreateDmAutomationResponse {
  automation?: DmAutomation;
}

/**
 * Response of updateDmAutomation
 */
export interface UpdateDmAutomationResponse {
  automation?: DmAutomation;
}

/**
 * Query parameters of deleteDmAutomation
 */
export interface DeleteDmAutomationQuery {
  workspace?: string;
}

/**
 * Query parameters of listDmAutomationRuns
 */
export interface ListDmAutomationRunsQuery {
  limit?: number;
  workspace?: string;
}

/**
 * Response of listDmAutomationRuns
 */
export interface ListDmAutomationRunsResponse {
  runs?: DmAutomationRun[];
}

/** One method per operation of the API, in the order of the spec */
export abstract class Operations extends Core {
  /**
   * List workspaces. `GET /v1/workspaces`
   */
  listWorkspaces(options?: RequestOptions): Promise<ListWorkspacesResponse> {
    return this.request("GET", `/v1/workspaces`, { options });
  }

  /**
   * Create a workspace. `POST /v1/workspaces`
   *
   * Creates a workspace owned by the API key's user, with the default posting schedule. A workspace per end customer keeps their accounts, posts and connect links apart. Counts toward the plan's workspace limit (100 on the Developer plan).
   *
   * Sends an Idempotency-Key (generated unless options.idempotencyKey is set) and retries safely with it.
   */
  createWorkspace(body: CreateWorkspaceBody, options?: RequestOptions): Promise<CreateWorkspaceResponse> {
    return this.request("POST", `/v1/workspaces`, { body, idempotent: true, options });
  }

  /**
   * Create a connect link. `POST /v1/connect-links`
   *
   * Creates a hosted page where someone without a Breakreach login (your end user, your client) connects social accounts into a workspace. Send them the url; they pick a network, authorize it, and come back to the page, then to redirectUrl when they click Done, with ?connected=<platforms>&workspace=<slug> appended. Accounts connected this way fire the account.connected webhook and count toward your plan. Only the workspace owner can create links.
   *
   * Sends an Idempotency-Key (generated unless options.idempotencyKey is set) and retries safely with it.
   */
  createConnectLink(body?: CreateConnectLinkBody, options?: RequestOptions): Promise<CreateConnectLinkResponse> {
    return this.request("POST", `/v1/connect-links`, { body, idempotent: true, workspace: "body", options });
  }

  /**
   * Get a connect link. `GET /v1/connect-links/{id}`
   *
   * Its status (active, expired or revoked) and the accounts connected through it. The url is only returned when the link is created.
   */
  getConnectLink(id: string, options?: RequestOptions): Promise<GetConnectLinkResponse> {
    return this.request("GET", `/v1/connect-links/${encodeURIComponent(id)}`, { options });
  }

  /**
   * Revoke a connect link. `DELETE /v1/connect-links/{id}`
   *
   * The page stops working at once. Accounts already connected through it stay connected.
   */
  revokeConnectLink(id: string, options?: RequestOptions): Promise<RevokeConnectLinkResponse> {
    return this.request("DELETE", `/v1/connect-links/${encodeURIComponent(id)}`, { options });
  }

  /**
   * List connected social accounts. `GET /v1/accounts`
   *
   * Returns the connected accounts of the workspace. Use the returned ids as accountIds when creating posts.
   */
  listAccounts(query?: ListAccountsQuery, options?: RequestOptions): Promise<ListAccountsResponse> {
    return this.request("GET", `/v1/accounts`, { query, workspace: "query", options });
  }

  /**
   * List posts. `GET /v1/posts`
   */
  listPosts(query?: ListPostsQuery, options?: RequestOptions): Promise<ListPostsResponse> {
    return this.request("GET", `/v1/posts`, { query, workspace: "query", options });
  }

  /**
   * Create a post (schedule, publish now or save a draft). `POST /v1/posts`
   *
   * Creates a post targeting one or several connected accounts. Provide scheduledAt (interpreted in the workspace timezone), or set useNextSlot to schedule at the next free slot of the workspace posting schedule, or publishNow to publish immediately. Set draft to save it for review in Breakreach without scheduling it: a draft needs no publish time (scheduledAt, if given, places it on the calendar), skips the media checks, and goes out only once it is scheduled, in the app or with PATCH /v1/posts/{id}. Media must be public URLs — use POST /v1/media first for reliable hosting. Media is required for Instagram, TikTok, YouTube and Pinterest. On Instagram one photo is a feed post, one video a Reel, and 2 to 10 files (photos and videos, in order) a carousel whose photos are all cropped to the first photo's shape. Facebook Pages take up to 10 photos in one post, or one video. LinkedIn posts one MP4 video alone, or turns 2 to 20 photos into a carousel (a PDF document, one page per photo, all cropped to the first photo's shape, titled with the first line), and posts a PDF URL as a document. Pinterest takes one image or one MP4/MOV video; an image sent with the video becomes its cover.
   *
   * Sends an Idempotency-Key (generated unless options.idempotencyKey is set) and retries safely with it.
   */
  createPost(body: CreatePostBody, options?: RequestOptions): Promise<CreatePostResponse> {
    return this.request("POST", `/v1/posts`, { body, idempotent: true, workspace: "body", options });
  }

  /**
   * Edit, schedule or move back to drafts. `PATCH /v1/posts/{id}`
   *
   * Edits a draft, scheduled or failed post. Only the fields you send change. Sending scheduledAt, useNextSlot or publishNow schedules the post: a draft goes out at that time, a failed post is retried. draft: true moves a scheduled post back to drafts so it won't publish. Published posts can't be edited.
   */
  updatePost(id: string, body: UpdatePostBody, options?: RequestOptions): Promise<UpdatePostResponse> {
    return this.request("PATCH", `/v1/posts/${encodeURIComponent(id)}`, { body, workspace: "body", options });
  }

  /**
   * Delete a post (cancels scheduling). `DELETE /v1/posts/{id}`
   */
  deletePost(id: string, query?: DeletePostQuery, options?: RequestOptions): Promise<DeletePostResponse> {
    return this.request("DELETE", `/v1/posts/${encodeURIComponent(id)}`, { query, workspace: "query", options });
  }

  /**
   * Re-host a media URL on Breakreach storage. `POST /v1/media`
   *
   * Downloads an image or video from a public URL and hosts it permanently, so it stays available for scheduled posts. Returns the hosted URL to use in POST /v1/posts.
   *
   * Sends an Idempotency-Key (generated unless options.idempotencyKey is set) and retries safely with it.
   */
  uploadMedia(body: UploadMediaBody, options?: RequestOptions): Promise<UploadMediaResponse> {
    return this.request("POST", `/v1/media`, { body, idempotent: true, options });
  }

  /**
   * Next free posting slot. `GET /v1/next-slot`
   *
   * Returns the earliest future time slot from the workspace posting schedule that has no post scheduled yet.
   */
  getNextSlot(query?: GetNextSlotQuery, options?: RequestOptions): Promise<GetNextSlotResponse> {
    return this.request("GET", `/v1/next-slot`, { query, workspace: "query", options });
  }

  /**
   * List Pinterest boards. `GET /v1/pinterest-boards`
   */
  listPinterestBoards(query?: ListPinterestBoardsQuery, options?: RequestOptions): Promise<ListPinterestBoardsResponse> {
    return this.request("GET", `/v1/pinterest-boards`, { query, workspace: "query", options });
  }

  /**
   * Workspace analytics. `GET /v1/analytics`
   *
   * Aggregated views, likes, comments and shares across the last 100 published posts, plus the top 10 posts by views.
   */
  getAnalytics(query?: GetAnalyticsQuery, options?: RequestOptions): Promise<GetAnalyticsResponse> {
    return this.request("GET", `/v1/analytics`, { query, workspace: "query", options });
  }

  /**
   * Account-level stats. `GET /v1/accounts/stats`
   *
   * Follower counts and account-level totals for every connected account, where the platform exposes them. Cached up to 1 hour.
   */
  getAccountStats(query?: GetAccountStatsQuery, options?: RequestOptions): Promise<JsonObject> {
    return this.request("GET", `/v1/accounts/stats`, { query, workspace: "query", options });
  }

  /**
   * Post insights. `GET /v1/post-insights`
   *
   * Everything about one post on a connected account, including posts not published with Breakreach: content, every lifetime metric the platform exposes (views, reach, reactions by type, clicks, saves, watch time, retention curve...), comments, and a comparison with the account's average. accountId and postId (platform post id) come from /v1/performance.
   */
  getPostInsights(query: GetPostInsightsQuery, options?: RequestOptions): Promise<JsonObject> {
    return this.request("GET", `/v1/post-insights`, { query, workspace: "query", options });
  }

  /**
   * Daily account trends. `GET /v1/accounts/trends`
   *
   * Daily account-level insights over the last N days (max 90): Facebook Pages (views, engagement, total followers), Instagram (reach) and Threads (views), with a summary per account. Cached up to 1 hour.
   */
  getAccountTrends(query?: GetAccountTrendsQuery, options?: RequestOptions): Promise<JsonObject> {
    return this.request("GET", `/v1/accounts/trends`, { query, workspace: "query", options });
  }

  /**
   * Per-post metrics. `GET /v1/posts/{id}/metrics`
   *
   * Views, likes, comments and shares for one post, plus the platform post ids it published to.
   */
  getPostMetrics(id: string, query?: GetPostMetricsQuery, options?: RequestOptions): Promise<GetPostMetricsResponse> {
    return this.request("GET", `/v1/posts/${encodeURIComponent(id)}/metrics`, { query, workspace: "query", options });
  }

  /**
   * Read comments on a published post. `GET /v1/posts/{id}/comments`
   *
   * Live comments/replies from the platforms. Supported: Instagram, Facebook, Threads, X. Each comment carries the accountId and platform needed to reply. YouTube is not listed yet: its comments need a restricted Google permission (youtube.force-ssl) that is not available to every account.
   */
  getPostComments(id: string, query?: GetPostCommentsQuery, options?: RequestOptions): Promise<JsonObject> {
    return this.request("GET", `/v1/posts/${encodeURIComponent(id)}/comments`, { query, workspace: "query", options });
  }

  /**
   * Recent comments. `GET /v1/comments`
   *
   * Comments on the latest 10 posts of every connected Instagram, Facebook and Threads account, including posts not published with Breakreach, plus replies to X posts published with Breakreach. Newest first. Each comment carries the accountId and platform needed to reply. YouTube is not listed yet: its comments need a restricted Google permission (youtube.force-ssl) that is not available to every account.
   */
  listRecentComments(query?: ListRecentCommentsQuery, options?: RequestOptions): Promise<JsonObject> {
    return this.request("GET", `/v1/comments`, { query, workspace: "query", options });
  }

  /**
   * Reply to a comment. `POST /v1/comments/reply`
   *
   * Replies to a comment on a published post. Supported: Instagram, Facebook, Threads, X. YouTube is not listed yet: its comments need a restricted Google permission (youtube.force-ssl) that is not available to every account.
   *
   * Sends an Idempotency-Key (generated unless options.idempotencyKey is set) and retries safely with it.
   */
  replyToComment(body: ReplyToCommentBody, options?: RequestOptions): Promise<JsonObject> {
    return this.request("POST", `/v1/comments/reply`, { body, idempotent: true, workspace: "body", options });
  }

  /**
   * Content performance. `GET /v1/performance`
   *
   * Per-post views, likes, comments, shares and engagement rate over the last N days (max 365), with totals per platform. Covers all posts on connected Instagram, Facebook, Threads, X, YouTube and Bluesky accounts, including posts not made with Breakreach. Cached up to 1 hour.
   */
  getContentPerformance(query?: GetContentPerformanceQuery, options?: RequestOptions): Promise<JsonObject> {
    return this.request("GET", `/v1/performance`, { query, workspace: "query", options });
  }

  /**
   * List direct message conversations. `GET /v1/inbox`
   *
   * Conversations on connected Facebook Pages (Messenger), Instagram and X accounts, newest first. Accounts whose messages can't be loaded are returned in errors with the reason.
   */
  listConversations(query?: ListConversationsQuery, options?: RequestOptions): Promise<JsonObject> {
    return this.request("GET", `/v1/inbox`, { query, workspace: "query", options });
  }

  /**
   * Read a conversation. `GET /v1/inbox/{conversationId}/messages`
   *
   * Messages of one conversation, oldest first. participantId is required for X.
   */
  getConversationMessages(conversationId: string, query: GetConversationMessagesQuery, options?: RequestOptions): Promise<JsonObject> {
    return this.request("GET", `/v1/inbox/${encodeURIComponent(conversationId)}/messages`, { query, workspace: "query", options });
  }

  /**
   * Send a direct message. `POST /v1/inbox/{conversationId}/messages`
   *
   * Replies in a conversation. Instagram and Messenger only accept replies within 24 hours of the person's last message. participantId is required for X.
   *
   * Sends an Idempotency-Key (generated unless options.idempotencyKey is set) and retries safely with it.
   */
  sendDirectMessage(conversationId: string, body: SendDirectMessageBody, options?: RequestOptions): Promise<JsonObject> {
    return this.request("POST", `/v1/inbox/${encodeURIComponent(conversationId)}/messages`, { body, idempotent: true, workspace: "body", options });
  }

  /**
   * List Comment to DM rules. `GET /v1/comment-dm-rules`
   *
   * Comment to DM automations: when someone comments a keyword on a post of an Instagram account or a Facebook Page (or any post of it), Breakreach sends them a DM through a private reply (Instagram Direct, or Messenger from the Page), and optionally a public reply under the comment. Both networks allow one private reply per comment within 7 days of it, and Breakreach sends each person one DM per rule.
   */
  listCommentDmRules(query?: ListCommentDmRulesQuery, options?: RequestOptions): Promise<ListCommentDmRulesResponse> {
    return this.request("GET", `/v1/comment-dm-rules`, { query, workspace: "query", options });
  }

  /**
   * Create a Comment to DM rule. `POST /v1/comment-dm-rules`
   *
   * Starts watching the comments of the account (Breakreach subscribes it to Instagram's comment webhooks, or the Page's feed webhooks). Requires an active plan or trial on the workspace.
   *
   * Sends an Idempotency-Key (generated unless options.idempotencyKey is set) and retries safely with it.
   */
  createCommentDmRule(body: CommentDmRuleInput, options?: RequestOptions): Promise<CreateCommentDmRuleResponse> {
    return this.request("POST", `/v1/comment-dm-rules`, { body, idempotent: true, workspace: "body", options });
  }

  /**
   * Latest posts of an Instagram account or a Facebook Page. `GET /v1/comment-dm-rules/media`
   *
   * The account's latest posts with their ids, to pick the mediaId of a rule.
   */
  listCommentDmMedia(query: ListCommentDmMediaQuery, options?: RequestOptions): Promise<JsonObject> {
    return this.request("GET", `/v1/comment-dm-rules/media`, { query, workspace: "query", options });
  }

  /**
   * Update a Comment to DM rule. `PATCH /v1/comment-dm-rules/{id}`
   *
   * Only the fields given change. active false pauses the rule; mediaId null makes it watch every post.
   */
  updateCommentDmRule(id: string, body: CommentDmRuleInput, options?: RequestOptions): Promise<UpdateCommentDmRuleResponse> {
    return this.request("PATCH", `/v1/comment-dm-rules/${encodeURIComponent(id)}`, { body, workspace: "body", options });
  }

  /**
   * Delete a Comment to DM rule. `DELETE /v1/comment-dm-rules/{id}`
   *
   * Deletes the rule with its activity.
   */
  deleteCommentDmRule(id: string, query?: DeleteCommentDmRuleQuery, options?: RequestOptions): Promise<JsonObject> {
    return this.request("DELETE", `/v1/comment-dm-rules/${encodeURIComponent(id)}`, { query, workspace: "query", options });
  }

  /**
   * Activity of a Comment to DM rule. `GET /v1/comment-dm-rules/{id}/events`
   *
   * Comments that matched the rule, newest first, kept 90 days: sent, failed (with the reason) or skipped. The same outcomes are pushed to webhooks subscribed to comment_dm.sent and comment_dm.failed.
   */
  listCommentDmEvents(id: string, query?: ListCommentDmEventsQuery, options?: RequestOptions): Promise<ListCommentDmEventsResponse> {
    return this.request("GET", `/v1/comment-dm-rules/${encodeURIComponent(id)}/events`, { query, workspace: "query", options });
  }

  /**
   * List DM automations. `GET /v1/dm-automations`
   *
   * DM automations: when someone DMs a keyword, mentions the account in their story, replies to a story or opens a ref link, Breakreach answers in Instagram Direct (or Messenger for a Facebook Page) and walks a flow of messages, waits, conditions and handoffs for that person. Replies only go out within Meta's 24-hour window after the person's last message; a person is in one flow at a time, and someone answering by hand stops it.
   */
  listDmAutomations(query?: ListDmAutomationsQuery, options?: RequestOptions): Promise<ListDmAutomationsResponse> {
    return this.request("GET", `/v1/dm-automations`, { query, workspace: "query", options });
  }

  /**
   * Create a DM automation. `POST /v1/dm-automations`
   *
   * Subscribes the account to Meta's message webhooks and starts answering. Requires an active plan or trial on the workspace.
   */
  createDmAutomation(body: DmAutomationInput, options?: RequestOptions): Promise<CreateDmAutomationResponse> {
    return this.request("POST", `/v1/dm-automations`, { body, workspace: "body", options });
  }

  /**
   * Update a DM automation. `PATCH /v1/dm-automations/{id}`
   *
   * Only the fields given change; steps replaces the whole flow (keep the ids of unchanged steps so people in the flow carry on). active false pauses it and stops the people in it.
   */
  updateDmAutomation(id: string, body: DmAutomationInput, options?: RequestOptions): Promise<UpdateDmAutomationResponse> {
    return this.request("PATCH", `/v1/dm-automations/${encodeURIComponent(id)}`, { body, workspace: "body", options });
  }

  /**
   * Delete a DM automation. `DELETE /v1/dm-automations/{id}`
   *
   * Deletes the automation with its runs; people in the flow stop.
   */
  deleteDmAutomation(id: string, query?: DeleteDmAutomationQuery, options?: RequestOptions): Promise<JsonObject> {
    return this.request("DELETE", `/v1/dm-automations/${encodeURIComponent(id)}`, { query, workspace: "query", options });
  }

  /**
   * Runs of a DM automation. `GET /v1/dm-automations/{id}/runs`
   *
   * Each person who went through it, newest first, kept 90 days: every step sent, choices tapped, clicks, and how it ended. Webhooks subscribed to dm_automation.started, dm_automation.handoff, dm_automation.finished and dm_automation.failed get the same events as they happen.
   */
  listDmAutomationRuns(id: string, query?: ListDmAutomationRunsQuery, options?: RequestOptions): Promise<ListDmAutomationRunsResponse> {
    return this.request("GET", `/v1/dm-automations/${encodeURIComponent(id)}/runs`, { query, workspace: "query", options });
  }
}
