// Generates the typed layer of both SDKs from the OpenAPI spec the API serves
// at https://api.breakreach.com/v1/openapi.json:
//   typescript/src/generated.ts          types + one method per operation
//   python/src/breakreach/_generated.py  TypedDicts + one method per operation
//   openapi.json                         the spec they were generated from
//
// In the monorepo the spec is read from apps/api/src/lib/openapi.ts; anywhere
// else (the public repo) from openapi.json, or from --spec <file|url>.
//
//   npx tsx scripts/generate.mts            write the files
//   npx tsx scripts/generate.mts --check    exit 1 when they are out of date
//
// Multipart operations are written by hand in each client (uploadMediaFile).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MONOREPO_SPEC = path.resolve(ROOT, "../apps/api/src/lib/openapi.ts");
const CHECK = process.argv.includes("--check");
const specArg = process.argv[process.argv.indexOf("--spec") + 1];

async function loadSpec(): Promise<any> {
  if (process.argv.includes("--spec") && specArg) {
    if (/^https?:/.test(specArg)) return (await fetch(specArg)).json();
    return JSON.parse(fs.readFileSync(specArg, "utf8"));
  }
  if (fs.existsSync(MONOREPO_SPEC)) return JSON.parse(JSON.stringify((await import(MONOREPO_SPEC)).openApiSpec));
  return JSON.parse(fs.readFileSync(path.join(ROOT, "openapi.json"), "utf8"));
}

const spec = await loadSpec();
const HANDWRITTEN = new Set(["uploadMediaFile"]);

// ── Shared walk over the operations ──────────────────────────────────────
type Param = { name: string; in: "path" | "query"; required: boolean; schema: any; description?: string };
type Op = {
  id: string;
  method: string;
  path: string;
  summary: string;
  description?: string;
  pathParams: Param[];
  query: Param[];
  body?: { schema: any; required: boolean };
  response?: any;
  idempotent: boolean;
  workspace?: "query" | "body";
};

const pascal = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
const snake = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").replace(/([A-Z])([A-Z][a-z])/g, "$1_$2").toLowerCase();
const refName = (ref: string) => ref.split("/").pop()!;
const deref = (s: any) => (s?.$ref ? spec.components.schemas[refName(s.$ref)] : s);

const ops: Op[] = [];
// Their response types are still generated, for the hand-written methods
const handwrittenResponses: Array<{ id: string; schema: any }> = [];
for (const [p, item] of Object.entries<any>(spec.paths)) {
  for (const method of ["get", "post", "patch", "delete"]) {
    const o = item[method];
    if (!o) continue;
    if (o.requestBody?.content?.["multipart/form-data"]) {
      if (!HANDWRITTEN.has(o.operationId)) throw new Error(`${o.operationId} is multipart: write it by hand in both clients, then add it to HANDWRITTEN`);
      handwrittenResponses.push({ id: o.operationId, schema: o.responses?.["200"]?.content?.["application/json"]?.schema });
      continue;
    }
    const params: any[] = o.parameters || [];
    const plain = params.filter((x) => !x.$ref) as Param[];
    const idempotent = params.some((x) => x.$ref?.endsWith("/IdempotencyKey"));
    const json = o.requestBody?.content?.["application/json"];
    const bodySchema = json ? deref(json.schema) : undefined;
    const query = plain.filter((x) => x.in === "query");
    const workspace = query.some((x) => x.name === "workspace") ? "query" : bodySchema?.properties?.workspace ? "body" : undefined;
    ops.push({
      id: o.operationId,
      method: method.toUpperCase(),
      path: p,
      summary: o.summary,
      description: o.description,
      pathParams: plain.filter((x) => x.in === "path"),
      query,
      body: json ? { schema: json.schema, required: !!o.requestBody.required } : undefined,
      response: o.responses?.["200"]?.content?.["application/json"]?.schema,
      idempotent,
      workspace,
    });
  }
}

const HEADER = "Generated by devkit/scripts/generate.mts from the Breakreach OpenAPI spec. Do not edit.";

// ── TypeScript ───────────────────────────────────────────────────────────
function tsDoc(lines: Array<string | undefined>, indent = "") {
  const text = lines.filter(Boolean).join("\n\n").replace(/\*\//g, "*\\/");
  if (!text) return "";
  const body = text.split("\n").map((l) => `${indent} *${l ? ` ${l}` : ""}`).join("\n");
  return `${indent}/**\n${body}\n${indent} */\n`;
}

function tsType(s: any, indent: string): string {
  if (!s) return "unknown";
  if (s.$ref) return refName(s.$ref);
  const types: string[] = Array.isArray(s.type) ? s.type : s.type ? [s.type] : [];
  if (s.enum) return [...s.enum.map((v: unknown) => JSON.stringify(v)), ...(types.includes("null") ? ["null"] : [])].join(" | ");
  if (!types.length) return s.properties ? tsObject(s, indent) : "unknown";
  return types
    .map((t) => {
      switch (t) {
        case "string": return s.format === "binary" ? "Blob" : "string";
        case "integer":
        case "number": return "number";
        case "boolean": return "boolean";
        case "null": return "null";
        case "array": {
          const inner = tsType(s.items, indent);
          return /^[\w.]+$/.test(inner) ? `${inner}[]` : `Array<${inner}>`;
        }
        case "object": return s.properties ? tsObject(s, indent) : "Record<string, unknown>";
        default: return "unknown";
      }
    })
    .join(" | ");
}

function tsObject(s: any, indent: string): string {
  const req = new Set<string>(s.required || []);
  const inner = indent + "  ";
  const fields = Object.entries<any>(s.properties || {}).map(
    ([k, v]) => `${tsDoc([v.description], inner)}${inner}${k}${req.has(k) ? "" : "?"}: ${tsType(v, inner)};`
  );
  return `{\n${fields.join("\n")}\n${indent}}`;
}

const tsNamed = (name: string, s: any, doc?: string) =>
  `${tsDoc([doc ?? s.description])}${s.type === "object" || s.properties ? `export interface ${name} ${tsObject(s, "")}` : `export type ${name} = ${tsType(s, "")};`}\n`;

function generateTs() {
  const out: string[] = [`// ${HEADER}\n// API version ${spec.info.version}\n`];
  out.push(`import { Core, type RequestOptions } from "./core";\n`);
  out.push(`/** A JSON object whose fields the spec doesn't list yet */\nexport type JsonObject = { [key: string]: any };\n`);
  for (const [name, s] of Object.entries<any>(spec.components.schemas)) out.push(tsNamed(name, s));
  for (const h of handwrittenResponses) out.push(tsNamed(`${pascal(h.id)}Response`, h.schema, `Response of ${h.id}`));

  const methods: string[] = [];
  for (const op of ops) {
    const P = pascal(op.id);
    let queryType: string | undefined;
    if (op.query.length) {
      queryType = `${P}Query`;
      out.push(tsNamed(queryType, { type: "object", required: op.query.filter((q) => q.required).map((q) => q.name), properties: Object.fromEntries(op.query.map((q) => [q.name, { ...q.schema, description: q.description ?? q.schema.description }])) }, `Query parameters of ${op.id}`));
    }
    let bodyType: string | undefined;
    if (op.body) {
      bodyType = op.body.schema.$ref ? refName(op.body.schema.$ref) : `${P}Body`;
      if (!op.body.schema.$ref) out.push(tsNamed(bodyType, op.body.schema, `Body of ${op.id}`));
    }
    let resType = "JsonObject";
    if (op.response?.$ref) resType = refName(op.response.$ref);
    else if (op.response?.properties) {
      resType = `${P}Response`;
      out.push(tsNamed(resType, op.response, `Response of ${op.id}`));
    }

    const args: string[] = op.pathParams.map((p) => `${p.name}: string`);
    const pathExpr = "`" + op.path.replace(/\{(\w+)\}/g, (_, n) => `\${encodeURIComponent(${n})}`) + "`";
    const parts: string[] = [];
    if (queryType) {
      args.push(`query${op.query.some((q) => q.required) ? "" : "?"}: ${queryType}`);
      parts.push("query");
    }
    if (bodyType) {
      args.push(`body${op.body!.required ? "" : "?"}: ${bodyType}`);
      parts.push("body");
    }
    args.push("options?: RequestOptions");
    if (op.idempotent) parts.push("idempotent: true");
    if (op.workspace) parts.push(`workspace: "${op.workspace}"`);
    parts.push("options");
    const doc = tsDoc([`${op.summary}. \`${op.method} ${op.path}\``, op.description, op.idempotent ? "Sends an Idempotency-Key (generated unless options.idempotencyKey is set) and retries safely with it." : undefined], "  ");
    methods.push(`${doc}  ${op.id}(${args.join(", ")}): Promise<${resType}> {\n    return this.request("${op.method}", ${pathExpr}, { ${parts.join(", ")} });\n  }`);
  }

  out.push(`/** One method per operation of the API, in the order of the spec */
export abstract class Operations extends Core {
${methods.join("\n\n")}
}
`);
  return out.join("\n");
}

// ── Python ───────────────────────────────────────────────────────────────
const PY_RESERVED = new Set(["from", "import", "class", "def", "global", "pass", "return", "type", "id", "lambda", "in", "is", "not", "and", "or", "for", "while"]);
const pyClasses: string[] = [];
const pyEmitted = new Set<string>();

function pyDoc(text: string | undefined, indent: string) {
  if (!text) return "";
  // a quote right before the closing """ would end the string early
  const escaped = text.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"').replace(/"$/, '\\"');
  return `${indent}"""${escaped.split("\n").map((l, i) => (i && l ? indent + l : l)).join("\n")}"""\n`;
}

function pyType(s: any, hint: string): string {
  if (!s) return "Any";
  if (s.$ref) return refName(s.$ref);
  const types: string[] = Array.isArray(s.type) ? s.type : s.type ? [s.type] : [];
  const nullable = types.includes("null");
  let base: string;
  if (s.enum) base = `Literal[${s.enum.map((v: unknown) => JSON.stringify(v)).join(", ")}]`;
  else {
    const t = types.find((x) => x !== "null");
    switch (t) {
      case "string": base = s.format === "binary" ? "bytes" : "str"; break;
      case "integer": base = "int"; break;
      case "number": base = "float"; break;
      case "boolean": base = "bool"; break;
      case "array": base = `List[${pyType(s.items, `${hint}Item`)}]`; break;
      case "object":
      case undefined:
        base = s.properties ? pyTypedDict(hint, s) : "Dict[str, Any]";
        break;
      default: base = "Any";
    }
  }
  return nullable ? `Optional[${base}]` : base;
}

function pyTypedDict(name: string, s: any, doc?: string): string {
  if (pyEmitted.has(name)) return name;
  pyEmitted.add(name);
  const fields = Object.entries<any>(s.properties || {}).map(([k, v]) => {
    const t = pyType(v, `${name}${pascal(k)}`);
    const note = v.description || "";
    return `    ${k}: ${t}${note ? `\n${pyDoc(note, "    ")}`.replace(/\n$/, "") : ""}`;
  });
  pyClasses.push(`class ${name}(TypedDict, total=False):\n${pyDoc(doc ?? s.description, "    ")}${fields.length ? fields.join("\n") : "    pass"}\n`);
  return name;
}

function pyArgName(n: string) {
  const s = snake(n);
  return PY_RESERVED.has(s) && s !== "id" ? `${s}_` : s;
}

function generatePy() {
  for (const [name, s] of Object.entries<any>(spec.components.schemas)) pyTypedDict(name, s);
  for (const h of handwrittenResponses) pyTypedDict(`${pascal(h.id)}Response`, h.schema, `Response of ${snake(h.id)}`);

  const methods: string[] = [];
  for (const op of ops) {
    const P = pascal(op.id);
    const sig: string[] = ["self", ...op.pathParams.map((p) => `${pyArgName(p.name)}: str`)];
    const kw: string[] = [];
    const queryMap: string[] = [];
    const bodyMap: string[] = [];
    const argDocs: string[] = [];

    for (const q of op.query) {
      const a = pyArgName(q.name);
      const t = pyType(q.schema, `${P}${pascal(q.name)}`);
      kw.push(q.required ? `${a}: ${t}` : `${a}: Union[${t}, NotGiven] = NOT_GIVEN`);
      queryMap.push(`"${q.name}": ${a}`);
      if (q.description) argDocs.push(`${a}: ${q.description}`);
    }
    if (op.body) {
      const schema = deref(op.body.schema);
      const req = new Set<string>(op.body.required ? schema.required || [] : []);
      const props = Object.entries<any>(schema.properties || {});
      // required ones first, Python wants them before the defaults
      props.sort(([a], [b]) => Number(req.has(b)) - Number(req.has(a)));
      for (const [k, v] of props) {
        const a = pyArgName(k);
        const t = pyType(v, `${P}${pascal(k)}`);
        kw.push(req.has(k) ? `${a}: ${t}` : `${a}: Union[${t}, NotGiven] = NOT_GIVEN`);
        bodyMap.push(`"${k}": ${a}`);
        if (v.description) argDocs.push(`${a}: ${v.description}`);
      }
    }
    if (op.idempotent) kw.push("idempotency_key: Optional[str] = None");
    kw.push("timeout: Optional[float] = None");
    if (kw.length) sig.push("*", ...kw);

    let resType = "Dict[str, Any]";
    if (op.response?.$ref) resType = refName(op.response.$ref);
    else if (op.response?.properties) resType = pyTypedDict(`${P}Response`, op.response, `Response of ${snake(op.id)}`);

    const pathExpr = op.pathParams.length
      ? `f"${op.path.replace(/\{(\w+)\}/g, (_, n) => `{_quote(${pyArgName(n)})}`)}"`
      : `"${op.path}"`;
    const call = [`"${op.method}"`, pathExpr];
    if (queryMap.length) call.push(`query={${queryMap.join(", ")}}`);
    if (bodyMap.length) call.push(`body={${bodyMap.join(", ")}}`);
    else if (op.body) call.push("body={}");
    if (op.idempotent) call.push("idempotent=True", "idempotency_key=idempotency_key");
    if (op.workspace) call.push(`workspace_in="${op.workspace}"`);
    call.push("timeout=timeout");

    const doc = [
      `${op.summary}. \`\`${op.method} ${op.path}\`\`.`,
      op.description,
      op.idempotent ? "Sends an Idempotency-Key (generated unless idempotency_key is given) and retries safely with it." : undefined,
      argDocs.length ? `Args:\n${argDocs.map((d) => `    ${d}`).join("\n")}` : undefined,
    ].filter(Boolean).join("\n\n");
    methods.push(`    def ${snake(op.id)}(\n        ${sig.join(",\n        ")},\n    ) -> ${resType}:\n${pyDoc(doc, "        ")}        return cast("${resType}", self._request(${call.join(", ")}))\n`);
  }

  return `# ${HEADER}
# API version ${spec.info.version}
# flake8: noqa
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, TypedDict, Union, cast
from urllib.parse import quote as _url_quote

from ._types import NOT_GIVEN, NotGiven


def _quote(value: str) -> str:
    return _url_quote(str(value), safe="")


${pyClasses.join("\n\n")}

class Operations:
    """One method per operation of the API, in the order of the spec"""

    def _request(self, method: str, path: str, *, query: Optional[Dict[str, Any]] = None, body: Optional[Dict[str, Any]] = None, idempotent: bool = False, idempotency_key: Optional[str] = None, workspace_in: Optional[str] = None, timeout: Optional[float] = None) -> Any:
        raise NotImplementedError

${methods.join("\n")}`;
}

// ── README method tables, between <!-- methods:start --> and <!-- methods:end --> ──
const uploadRow = { id: "uploadMediaFile", method: "POST", path: "/v1/media/upload", summary: "Upload a local file to Breakreach storage" };
const rows = [...ops.map((o) => ({ id: o.id, method: o.method, path: o.path, summary: o.summary }))];
rows.splice(rows.findIndex((r) => r.id === "uploadMedia") + 1, 0, uploadRow);

function readmeWithMethods(rel: string, name: (id: string) => string) {
  const file = path.join(ROOT, rel);
  const readme = fs.readFileSync(file, "utf8");
  const table = [
    "| Method | Endpoint | |",
    "| --- | --- | --- |",
    ...rows.map((r) => `| \`${name(r.id)}\` | \`${r.method} ${r.path}\` | ${r.summary} |`),
  ].join("\n");
  return readme.replace(/<!-- methods:start -->[\s\S]*<!-- methods:end -->/, `<!-- methods:start -->\n${table}\n<!-- methods:end -->`);
}

// ── Write or check ───────────────────────────────────────────────────────
const files: Record<string, string> = {
  "typescript/src/generated.ts": generateTs(),
  "python/src/breakreach/_generated.py": generatePy(),
  "openapi.json": JSON.stringify(spec, null, 2) + "\n",
  "typescript/README.md": readmeWithMethods("typescript/README.md", (id) => `${id}()`),
  "python/README.md": readmeWithMethods("python/README.md", (id) => `${snake(id)}()`),
};

let stale = 0;
for (const [rel, content] of Object.entries(files)) {
  const file = path.join(ROOT, rel);
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
  if (current === content) continue;
  stale++;
  if (CHECK) console.error(`out of date: ${rel}`);
  else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log(`wrote ${rel}`);
  }
}
console.log(`${ops.length} operations (+ ${HANDWRITTEN.size} written by hand), API ${spec.info.version}`);
if (CHECK && stale) process.exit(1);
