# Generated by devkit/scripts/generate.mts from the Breakreach OpenAPI spec. Do not edit.
# API version 1.1.0
# flake8: noqa
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, TypedDict, Union, cast
from urllib.parse import quote as _url_quote

from ._types import NOT_GIVEN, NotGiven


def _quote(value: str) -> str:
    return _url_quote(str(value), safe="")


class PostMetrics(TypedDict, total=False):
    views: float
    likes: float
    comments: float
    shares: float


class Post(TypedDict, total=False):
    id: str
    content: str
    status: Literal["draft", "scheduled", "publishing", "published", "failed"]
    scheduledAt: str
    accountIds: List[str]
    media: List[str]
    metrics: Optional[PostMetrics]
    error: Optional[str]
    """Human-readable failure reason when status is failed"""


class Account(TypedDict, total=False):
    id: str
    platform: Literal["instagram", "tiktok", "x", "reddit", "linkedin", "youtube", "facebook", "threads", "bluesky", "pinterest", "telegram", "discord", "slack", "mastodon", "wordpress", "ghost", "devto", "hashnode", "tumblr"]
    displayName: str
    warning: str
    """Present when the account's authorization has expired, was revoked on the network's side, or expires soon (LinkedIn lasts about 60 days): the user must reconnect it in Breakreach settings"""


class Workspace(TypedDict, total=False):
    slug: str
    name: str
    timezone: str


class ArticleSettings(TypedDict, total=False):
    """Options for the blog networks (Dev.to, Hashnode, Ghost, Tumblr). On Dev.to, Hashnode and Ghost the first line of content is the title and the rest the body, in Markdown; the first photo is the cover"""
    tags: List[str]
    """Dev.to keeps the first 4 (letters and digits), Hashnode 15, Ghost and Tumblr all"""
    canonicalUrl: str
    """Where the article was first published, when this is a copy (Dev.to, Hashnode, Ghost)"""
    asDraft: bool
    """Create it as an unpublished draft on the blog instead of publishing it"""
    newsletter: str
    """Ghost: also email the post with this newsletter (its slug, or "default" for the site's first active one)"""
    emailSegment: Literal["all", "status:free", "status:-free"]
    """Ghost newsletter: who gets the email (default all members)"""
    aiDisclosure: Literal["no_ai", "some_ai", "fully_autonomous"]
    """Dev.to: how much AI wrote the article (Dev.to asks API clients to say so accurately)"""


class CreatedPost(TypedDict, total=False):
    id: str
    status: Literal["draft", "scheduled", "publishing"]
    """publishing when publishNow was set, draft when draft was set"""
    scheduledAt: str
    """Publish time, in UTC"""
    accounts: List[str]
    """Target accounts as "platform (display name)", e.g. "instagram (Acme)\""""


class ConnectLinkConnectedItem(TypedDict, total=False):
    accountId: str
    platform: str
    displayName: str
    connectedAt: str


class ConnectLink(TypedDict, total=False):
    id: str
    url: str
    """The page to send, only returned at creation"""
    workspace: str
    """Workspace slug"""
    platforms: List[str]
    redirectUrl: Optional[str]
    expiresAt: str
    status: Literal["active", "expired", "revoked"]
    connected: List[ConnectLinkConnectedItem]


class CommentDmRuleAccount(TypedDict, total=False):
    displayName: str
    avatarUrl: Optional[str]


class CommentDmRuleMedia(TypedDict, total=False):
    caption: str
    thumbnailUrl: Optional[str]
    permalink: Optional[str]
    timestamp: Optional[str]


class CommentDmRuleStats(TypedDict, total=False):
    triggered: int
    sent: int
    failed: int


class CommentDmRule(TypedDict, total=False):
    id: str
    accountId: str
    platform: Literal["instagram", "facebook"]
    account: CommentDmRuleAccount
    mediaId: Optional[str]
    """The Instagram or Facebook post the rule watches; null = every post of the account"""
    media: Optional[CommentDmRuleMedia]
    keywords: List[str]
    """Empty = every comment triggers the rule"""
    match: Literal["contains", "exact"]
    dmText: str
    publicReplies: List[str]
    active: bool
    stats: CommentDmRuleStats
    lastTriggeredAt: Optional[str]
    createdAt: str
    updatedAt: str


class CommentDmRuleInput(TypedDict, total=False):
    accountId: str
    """Instagram account or Facebook Page id from /v1/accounts (create only, a rule can't change account)"""
    mediaId: Optional[str]
    """Instagram or Facebook post id to watch (from /v1/comment-dm-rules/media or the postId of /v1/comments). Omit or null for every post"""
    postId: str
    """Instead of mediaId: a Breakreach post id published on this account"""
    keywords: List[str]
    """Words or phrases that trigger the DM, case and accents ignored. Empty = every comment"""
    match: Literal["contains", "exact"]
    """contains = the keyword appears as a whole word or phrase; exact = the comment is just the keyword (punctuation and emoji around it ignored)"""
    dmText: str
    """The DM sent to the commenter, links allowed. {username} becomes their @handle on Instagram, their first name on Facebook. Required on create"""
    publicReplies: List[str]
    """Optional public replies under the comment once the DM is sent, one picked at random. {username} becomes their @handle on Instagram, their first name on Facebook"""
    active: bool
    workspace: str


class CommentDmEvent(TypedDict, total=False):
    id: str
    ruleId: str
    status: Literal["pending", "sent", "failed", "skipped"]
    reason: Optional[str]
    """Why it was skipped: duplicate (the person already got this rule's DM), too_old (Instagram allows private replies within 7 days), plan (no active plan), paused, deleted"""
    error: Optional[str]
    commentId: str
    commentText: str
    commenterUsername: Optional[str]
    """Instagram handle"""
    commenterName: Optional[str]
    """Facebook name"""
    mediaId: Optional[str]
    dmMessageId: Optional[str]
    publicReply: Optional[str]
    """The public reply posted under the comment"""
    publicReplyError: Optional[str]
    createdAt: str
    sentAt: Optional[str]


class DmTrigger(TypedDict, total=False):
    type: Literal["keyword", "any_message", "story_mention", "story_reply", "ref"]
    """keyword = a DM containing a keyword; any_message = any DM (welcome or away reply); story_mention = someone mentions the account in their story (Instagram); story_reply = a reply to one of its stories, optionally with keywords (Instagram); ref = someone opens ig.me/m/<username>?ref=<ref> or m.me/<page id>?ref=<ref> and writes"""
    keywords: List[str]
    """keyword (required) and story_reply (optional); case and accents ignored"""
    match: Literal["contains", "exact"]
    ref: Optional[str]


class DmStepButton(TypedDict, total=False):
    """message: a link button; clicks are counted (the link goes through api.breakreach.com/l/...)"""
    title: str
    url: str


class DmStepChoicesItem(TypedDict, total=False):
    id: str
    label: str
    steps: List[DmStep]


class DmStepOtherwise(TypedDict, total=False):
    """message with choices: a typed answer that isn't a choice, or no answer within afterMinutes"""
    afterMinutes: int
    steps: List[DmStep]


class DmStep(TypedDict, total=False):
    """One step of a flow. A message with choices, a condition and a handoff must be the last step of their list; what follows goes inside their branches. Up to 40 steps, branches 6 levels deep."""
    id: str
    """Kept across edits so people in the flow carry on; generated when omitted"""
    type: Literal["message", "wait", "condition", "handoff"]
    text: str
    """message: up to 1000 bytes (640 characters with a button). {username} = their @handle on Instagram, first name on Messenger; {first_name}"""
    button: Optional[DmStepButton]
    """message: a link button; clicks are counted (the link goes through api.breakreach.com/l/...)"""
    choices: List[DmStepChoicesItem]
    """message: quick-reply choices, each with its own steps. Not with a button"""
    otherwise: Optional[DmStepOtherwise]
    """message with choices: a typed answer that isn't a choice, or no answer within afterMinutes"""
    minutes: int
    """wait"""
    check: Literal["replied", "keyword", "clicked", "follows"]
    """condition: a reply, a reply containing keywords, a click on an earlier link button (each waited for up to withinMinutes), or whether they follow the account (Instagram, checked at once)"""
    keywords: List[str]
    match: Literal["contains", "exact"]
    withinMinutes: int
    yes: List[DmStep]
    no: List[DmStep]
    note: str
    """handoff: shown in the Inbox"""


class DmAutomationAccount(TypedDict, total=False):
    displayName: str
    avatarUrl: Optional[str]


class DmAutomationStats(TypedDict, total=False):
    started: int
    completed: int
    handedOff: int
    clicks: int
    failed: int


class DmAutomation(TypedDict, total=False):
    id: str
    accountId: str
    platform: Literal["instagram", "facebook"]
    account: DmAutomationAccount
    name: str
    trigger: DmTrigger
    refLink: Optional[str]
    """For a ref trigger: the link to share (link in bio, QR code, ad)"""
    steps: List[DmStep]
    reentry: Literal["once", "always"]
    cooldownHours: int
    active: bool
    stats: DmAutomationStats
    lastTriggeredAt: Optional[str]
    createdAt: str
    updatedAt: str


class DmAutomationInput(TypedDict, total=False):
    accountId: str
    """Instagram account or Facebook Page id from /v1/accounts (create only)"""
    name: str
    trigger: DmTrigger
    steps: List[DmStep]
    """Required on create. On update, the whole list"""
    reentry: Literal["once", "always"]
    """once = a person goes through it once; always = each time they trigger it, at most once per cooldownHours"""
    cooldownHours: int
    active: bool
    workspace: str


class DmAutomationRunContact(TypedDict, total=False):
    id: str
    """Instagram-scoped or Page-scoped id"""
    username: Optional[str]
    name: Optional[str]


class DmAutomationRunTrigger(TypedDict, total=False):
    type: str
    text: Optional[str]
    ref: Optional[str]


class DmAutomationRunWaiting(TypedDict, total=False):
    kind: Literal["timer", "choice", "reply", "click"]
    stepId: str
    until: str


class DmAutomationRunLogItem(TypedDict, total=False):
    at: str
    kind: str
    """trigger, sent, choice, reply, click, branch, wait, waited, handoff, end, error"""
    stepId: Optional[str]
    text: Optional[str]
    detail: Optional[str]


class DmAutomationRun(TypedDict, total=False):
    id: str
    automationId: str
    status: Literal["running", "waiting", "completed", "handed_off", "stopped", "window_closed", "failed"]
    contact: DmAutomationRunContact
    trigger: DmAutomationRunTrigger
    stepId: Optional[str]
    waiting: Optional[DmAutomationRunWaiting]
    clicks: int
    log: List[DmAutomationRunLogItem]
    endReason: Optional[str]
    """done, handoff, human_replied (someone answered by hand), window (Meta's 24-hour window closed), paused, deleted, flow_changed, stopped_by_team, send, account"""
    error: Optional[str]
    createdAt: str
    endedAt: Optional[str]


class Error(TypedDict, total=False):
    error: str
    """Human-readable reason"""


class UploadMediaFileResponse(TypedDict, total=False):
    """Response of upload_media_file"""
    url: str


class ListWorkspacesResponse(TypedDict, total=False):
    """Response of list_workspaces"""
    workspaces: List[Workspace]


class CreateWorkspaceResponse(TypedDict, total=False):
    """Response of create_workspace"""
    workspace: Workspace


class CreateConnectLinkResponse(TypedDict, total=False):
    """Response of create_connect_link"""
    connectLink: ConnectLink


class GetConnectLinkResponse(TypedDict, total=False):
    """Response of get_connect_link"""
    connectLink: ConnectLink


class RevokeConnectLinkResponse(TypedDict, total=False):
    """Response of revoke_connect_link"""
    connectLink: ConnectLink


class ListAccountsResponse(TypedDict, total=False):
    """Response of list_accounts"""
    accounts: List[Account]
    message: str
    """Present only when no account is connected: explains how to connect one, with the link to the workspace settings"""


class ListPostsResponse(TypedDict, total=False):
    """Response of list_posts"""
    posts: List[Post]


class CreatePostTiktokSettings(TypedDict, total=False):
    privacyLevel: Literal["PUBLIC_TO_EVERYONE", "MUTUAL_FOLLOW_FRIENDS", "FOLLOWER_OF_CREATOR", "SELF_ONLY"]
    disableComment: bool
    disableDuet: bool
    disableStitch: bool


class CreatePostResponse(TypedDict, total=False):
    """Response of create_post"""
    post: CreatedPost


class UpdatePostResponse(TypedDict, total=False):
    """Response of update_post"""
    post: CreatedPost


class DeletePostResponse(TypedDict, total=False):
    """Response of delete_post"""
    ok: bool


class UploadMediaResponse(TypedDict, total=False):
    """Response of upload_media"""
    url: str


class GetNextSlotResponse(TypedDict, total=False):
    """Response of get_next_slot"""
    scheduledAt: str
    """Local time in the workspace timezone, to pass as scheduledAt"""
    timezone: str
    utc: str


class ListPinterestBoardsResponseBoardsItem(TypedDict, total=False):
    id: str
    name: str


class ListPinterestBoardsResponse(TypedDict, total=False):
    """Response of list_pinterest_boards"""
    accountId: str
    boards: List[ListPinterestBoardsResponseBoardsItem]


class GetAnalyticsResponseTotals(TypedDict, total=False):
    views: float
    likes: float
    comments: float
    shares: float
    posts: int


class GetAnalyticsResponseTopPostsItemMetrics(TypedDict, total=False):
    views: float
    likes: float
    comments: float
    shares: float


class GetAnalyticsResponseTopPostsItem(TypedDict, total=False):
    id: str
    content: str
    metrics: Optional[GetAnalyticsResponseTopPostsItemMetrics]


class GetAnalyticsResponse(TypedDict, total=False):
    """Response of get_analytics"""
    totals: GetAnalyticsResponseTotals
    topPosts: List[GetAnalyticsResponseTopPostsItem]


class GetPostMetricsResponseMetrics(TypedDict, total=False):
    views: float
    likes: float
    comments: float
    shares: float


class GetPostMetricsResponsePerPlatformItem(TypedDict, total=False):
    accountId: str
    platform: str
    platformPostId: str


class GetPostMetricsResponse(TypedDict, total=False):
    """Response of get_post_metrics"""
    id: str
    status: str
    publishedAt: Optional[str]
    metrics: Optional[GetPostMetricsResponseMetrics]
    perPlatform: List[GetPostMetricsResponsePerPlatformItem]
    error: Optional[str]


class ListCommentDmRulesResponse(TypedDict, total=False):
    """Response of list_comment_dm_rules"""
    rules: List[CommentDmRule]


class CreateCommentDmRuleResponse(TypedDict, total=False):
    """Response of create_comment_dm_rule"""
    rule: CommentDmRule


class UpdateCommentDmRuleResponse(TypedDict, total=False):
    """Response of update_comment_dm_rule"""
    rule: CommentDmRule


class ListCommentDmEventsResponse(TypedDict, total=False):
    """Response of list_comment_dm_events"""
    events: List[CommentDmEvent]


class ListDmAutomationsResponse(TypedDict, total=False):
    """Response of list_dm_automations"""
    automations: List[DmAutomation]


class CreateDmAutomationResponse(TypedDict, total=False):
    """Response of create_dm_automation"""
    automation: DmAutomation


class UpdateDmAutomationResponse(TypedDict, total=False):
    """Response of update_dm_automation"""
    automation: DmAutomation


class ListDmAutomationRunsResponse(TypedDict, total=False):
    """Response of list_dm_automation_runs"""
    runs: List[DmAutomationRun]


class Operations:
    """One method per operation of the API, in the order of the spec"""

    def _request(self, method: str, path: str, *, query: Optional[Dict[str, Any]] = None, body: Optional[Dict[str, Any]] = None, idempotent: bool = False, idempotency_key: Optional[str] = None, workspace_in: Optional[str] = None, timeout: Optional[float] = None) -> Any:
        raise NotImplementedError

    def list_workspaces(
        self,
        *,
        timeout: Optional[float] = None,
    ) -> ListWorkspacesResponse:
        """List workspaces. ``GET /v1/workspaces``."""
        return cast("ListWorkspacesResponse", self._request("GET", "/v1/workspaces", timeout=timeout))

    def create_workspace(
        self,
        *,
        name: str,
        timezone: Union[str, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> CreateWorkspaceResponse:
        """Create a workspace. ``POST /v1/workspaces``.

        Creates a workspace owned by the API key's user, with the default posting schedule. A workspace per end customer keeps their accounts, posts and connect links apart. Counts toward the plan's workspace limit (100 on the Developer plan).

        Sends an Idempotency-Key (generated unless idempotency_key is given) and retries safely with it.

        Args:
            name: Up to 80 characters
            timezone: IANA timezone used to read scheduledAt, e.g. Europe/Paris (default UTC)"""
        return cast("CreateWorkspaceResponse", self._request("POST", "/v1/workspaces", body={"name": name, "timezone": timezone}, idempotent=True, idempotency_key=idempotency_key, timeout=timeout))

    def create_connect_link(
        self,
        *,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        platforms: Union[List[Literal["instagram", "facebook", "threads", "tiktok", "linkedin", "youtube", "x", "pinterest", "bluesky", "reddit", "telegram", "discord", "slack", "mastodon", "wordpress", "ghost", "devto", "hashnode", "tumblr"]], NotGiven] = NOT_GIVEN,
        redirect_url: Union[str, NotGiven] = NOT_GIVEN,
        expires_in_hours: Union[int, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> CreateConnectLinkResponse:
        """Create a connect link. ``POST /v1/connect-links``.

        Creates a hosted page where someone without a Breakreach login (your end user, your client) connects social accounts into a workspace. Send them the url; they pick a network, authorize it, and come back to the page, then to redirectUrl when they click Done, with ?connected=<platforms>&workspace=<slug> appended. Accounts connected this way fire the account.connected webhook and count toward your plan. Only the workspace owner can create links.

        Sends an Idempotency-Key (generated unless idempotency_key is given) and retries safely with it.

        Args:
            workspace: Workspace slug (optional, defaults to your first workspace)
            platforms: Networks offered on the page (default: all)
            redirect_url: Where the Done button sends them: https, or http on localhost
            expires_in_hours: How long the link works (default 24)"""
        return cast("CreateConnectLinkResponse", self._request("POST", "/v1/connect-links", body={"workspace": workspace, "platforms": platforms, "redirectUrl": redirect_url, "expiresInHours": expires_in_hours}, idempotent=True, idempotency_key=idempotency_key, workspace_in="body", timeout=timeout))

    def get_connect_link(
        self,
        id: str,
        *,
        timeout: Optional[float] = None,
    ) -> GetConnectLinkResponse:
        """Get a connect link. ``GET /v1/connect-links/{id}``.

        Its status (active, expired or revoked) and the accounts connected through it. The url is only returned when the link is created."""
        return cast("GetConnectLinkResponse", self._request("GET", f"/v1/connect-links/{_quote(id)}", timeout=timeout))

    def revoke_connect_link(
        self,
        id: str,
        *,
        timeout: Optional[float] = None,
    ) -> RevokeConnectLinkResponse:
        """Revoke a connect link. ``DELETE /v1/connect-links/{id}``.

        The page stops working at once. Accounts already connected through it stay connected."""
        return cast("RevokeConnectLinkResponse", self._request("DELETE", f"/v1/connect-links/{_quote(id)}", timeout=timeout))

    def list_accounts(
        self,
        *,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> ListAccountsResponse:
        """List connected social accounts. ``GET /v1/accounts``.

        Returns the connected accounts of the workspace. Use the returned ids as accountIds when creating posts.

        Args:
            workspace: Workspace slug (defaults to your first workspace)"""
        return cast("ListAccountsResponse", self._request("GET", "/v1/accounts", query={"workspace": workspace}, workspace_in="query", timeout=timeout))

    def list_posts(
        self,
        *,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        status: Union[Literal["draft", "scheduled", "published", "failed", "all"], NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> ListPostsResponse:
        """List posts. ``GET /v1/posts``."""
        return cast("ListPostsResponse", self._request("GET", "/v1/posts", query={"workspace": workspace, "status": status, "limit": limit}, workspace_in="query", timeout=timeout))

    def create_post(
        self,
        *,
        content: str,
        account_ids: List[str],
        scheduled_at: Union[str, NotGiven] = NOT_GIVEN,
        publish_now: Union[bool, NotGiven] = NOT_GIVEN,
        use_next_slot: Union[bool, NotGiven] = NOT_GIVEN,
        draft: Union[bool, NotGiven] = NOT_GIVEN,
        media: Union[List[str], NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        pinterest_board_id: Union[str, NotGiven] = NOT_GIVEN,
        pinterest_link: Union[str, NotGiven] = NOT_GIVEN,
        reddit_subreddit: Union[str, NotGiven] = NOT_GIVEN,
        reddit_flair_text: Union[str, NotGiven] = NOT_GIVEN,
        article_settings: Union[ArticleSettings, NotGiven] = NOT_GIVEN,
        tiktok_settings: Union[CreatePostTiktokSettings, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> CreatePostResponse:
        """Create a post (schedule, publish now or save a draft). ``POST /v1/posts``.

        Creates a post targeting one or several connected accounts. Provide scheduledAt (interpreted in the workspace timezone), or set useNextSlot to schedule at the next free slot of the workspace posting schedule, or publishNow to publish immediately. Set draft to save it for review in Breakreach without scheduling it: a draft needs no publish time (scheduledAt, if given, places it on the calendar), skips the media checks, and goes out only once it is scheduled, in the app or with PATCH /v1/posts/{id}. Media must be public URLs — use POST /v1/media first for reliable hosting. Media is required for Instagram, TikTok, YouTube and Pinterest. On Instagram one photo is a feed post, one video a Reel, and 2 to 10 files (photos and videos, in order) a carousel whose photos are all cropped to the first photo's shape. Facebook Pages take up to 10 photos in one post, or one video. LinkedIn posts one MP4 video alone, or turns 2 to 20 photos into a carousel (a PDF document, one page per photo, all cropped to the first photo's shape, titled with the first line), and posts a PDF URL as a document. Pinterest takes one image or one MP4/MOV video; an image sent with the video becomes its cover.

        Sends an Idempotency-Key (generated unless idempotency_key is given) and retries safely with it.

        Args:
            content: The post text. For Reddit, the first line becomes the title.
            account_ids: Target account ids from GET /v1/accounts
            scheduled_at: ISO datetime in the workspace timezone, e.g. 2026-09-20T11:00:00
            draft: Save as a draft for review instead of scheduling it. Can't be combined with publishNow
            workspace: Workspace slug (optional)
            pinterest_board_id: Required when targeting Pinterest — see GET /v1/pinterest-boards
            pinterest_link: Destination URL of the pin (optional, http(s), up to 2,048 characters). The pin title is the first line of content
            reddit_subreddit: Subreddit without r/ — defaults to the user profile
            reddit_flair_text: Post flair name when the subreddit requires one"""
        return cast("CreatePostResponse", self._request("POST", "/v1/posts", body={"content": content, "accountIds": account_ids, "scheduledAt": scheduled_at, "publishNow": publish_now, "useNextSlot": use_next_slot, "draft": draft, "media": media, "workspace": workspace, "pinterestBoardId": pinterest_board_id, "pinterestLink": pinterest_link, "redditSubreddit": reddit_subreddit, "redditFlairText": reddit_flair_text, "articleSettings": article_settings, "tiktokSettings": tiktok_settings}, idempotent=True, idempotency_key=idempotency_key, workspace_in="body", timeout=timeout))

    def update_post(
        self,
        id: str,
        *,
        content: Union[str, NotGiven] = NOT_GIVEN,
        account_ids: Union[List[str], NotGiven] = NOT_GIVEN,
        media: Union[List[str], NotGiven] = NOT_GIVEN,
        scheduled_at: Union[str, NotGiven] = NOT_GIVEN,
        publish_now: Union[bool, NotGiven] = NOT_GIVEN,
        use_next_slot: Union[bool, NotGiven] = NOT_GIVEN,
        draft: Union[bool, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        pinterest_board_id: Union[str, NotGiven] = NOT_GIVEN,
        pinterest_link: Union[str, NotGiven] = NOT_GIVEN,
        reddit_subreddit: Union[str, NotGiven] = NOT_GIVEN,
        reddit_flair_text: Union[str, NotGiven] = NOT_GIVEN,
        article_settings: Union[ArticleSettings, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> UpdatePostResponse:
        """Edit, schedule or move back to drafts. ``PATCH /v1/posts/{id}``.

        Edits a draft, scheduled or failed post. Only the fields you send change. Sending scheduledAt, useNextSlot or publishNow schedules the post: a draft goes out at that time, a failed post is retried. draft: true moves a scheduled post back to drafts so it won't publish. Published posts can't be edited.

        Args:
            account_ids: Replaces the target accounts
            media: Replaces the media
            scheduled_at: ISO datetime in the workspace timezone, e.g. 2026-09-20T11:00:00
            draft: true moves the post back to drafts
            workspace: Workspace slug (optional)"""
        return cast("UpdatePostResponse", self._request("PATCH", f"/v1/posts/{_quote(id)}", body={"content": content, "accountIds": account_ids, "media": media, "scheduledAt": scheduled_at, "publishNow": publish_now, "useNextSlot": use_next_slot, "draft": draft, "workspace": workspace, "pinterestBoardId": pinterest_board_id, "pinterestLink": pinterest_link, "redditSubreddit": reddit_subreddit, "redditFlairText": reddit_flair_text, "articleSettings": article_settings}, workspace_in="body", timeout=timeout))

    def delete_post(
        self,
        id: str,
        *,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> DeletePostResponse:
        """Delete a post (cancels scheduling). ``DELETE /v1/posts/{id}``."""
        return cast("DeletePostResponse", self._request("DELETE", f"/v1/posts/{_quote(id)}", query={"workspace": workspace}, workspace_in="query", timeout=timeout))

    def upload_media(
        self,
        *,
        url: str,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> UploadMediaResponse:
        """Re-host a media URL on Breakreach storage. ``POST /v1/media``.

        Downloads an image or video from a public URL and hosts it permanently, so it stays available for scheduled posts. Returns the hosted URL to use in POST /v1/posts.

        Sends an Idempotency-Key (generated unless idempotency_key is given) and retries safely with it."""
        return cast("UploadMediaResponse", self._request("POST", "/v1/media", body={"url": url}, idempotent=True, idempotency_key=idempotency_key, timeout=timeout))

    def get_next_slot(
        self,
        *,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> GetNextSlotResponse:
        """Next free posting slot. ``GET /v1/next-slot``.

        Returns the earliest future time slot from the workspace posting schedule that has no post scheduled yet."""
        return cast("GetNextSlotResponse", self._request("GET", "/v1/next-slot", query={"workspace": workspace}, workspace_in="query", timeout=timeout))

    def list_pinterest_boards(
        self,
        *,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> ListPinterestBoardsResponse:
        """List Pinterest boards. ``GET /v1/pinterest-boards``."""
        return cast("ListPinterestBoardsResponse", self._request("GET", "/v1/pinterest-boards", query={"workspace": workspace}, workspace_in="query", timeout=timeout))

    def get_analytics(
        self,
        *,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> GetAnalyticsResponse:
        """Workspace analytics. ``GET /v1/analytics``.

        Aggregated views, likes, comments and shares across the last 100 published posts, plus the top 10 posts by views."""
        return cast("GetAnalyticsResponse", self._request("GET", "/v1/analytics", query={"workspace": workspace}, workspace_in="query", timeout=timeout))

    def get_account_stats(
        self,
        *,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Account-level stats. ``GET /v1/accounts/stats``.

        Follower counts and account-level totals for every connected account, where the platform exposes them. Cached up to 1 hour."""
        return cast("Dict[str, Any]", self._request("GET", "/v1/accounts/stats", query={"workspace": workspace}, workspace_in="query", timeout=timeout))

    def get_post_insights(
        self,
        *,
        account_id: str,
        post_id: str,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Post insights. ``GET /v1/post-insights``.

        Everything about one post on a connected account, including posts not published with Breakreach: content, every lifetime metric the platform exposes (views, reach, reactions by type, clicks, saves, watch time, retention curve...), comments, and a comparison with the account's average. accountId and postId (platform post id) come from /v1/performance.

        Args:
            post_id: Platform post id"""
        return cast("Dict[str, Any]", self._request("GET", "/v1/post-insights", query={"accountId": account_id, "postId": post_id, "workspace": workspace}, workspace_in="query", timeout=timeout))

    def get_account_trends(
        self,
        *,
        days: Union[int, NotGiven] = NOT_GIVEN,
        account_id: Union[str, NotGiven] = NOT_GIVEN,
        refresh: Union[bool, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Daily account trends. ``GET /v1/accounts/trends``.

        Daily account-level insights over the last N days (max 90): Facebook Pages (views, engagement, total followers), Instagram (reach) and Threads (views), with a summary per account. Cached up to 1 hour."""
        return cast("Dict[str, Any]", self._request("GET", "/v1/accounts/trends", query={"days": days, "accountId": account_id, "refresh": refresh, "workspace": workspace}, workspace_in="query", timeout=timeout))

    def get_post_metrics(
        self,
        id: str,
        *,
        refresh: Union[bool, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> GetPostMetricsResponse:
        """Per-post metrics. ``GET /v1/posts/{id}/metrics``.

        Views, likes, comments and shares for one post, plus the platform post ids it published to.

        Args:
            refresh: Fetch fresh metrics from the platforms before answering, instead of the last stored ones"""
        return cast("GetPostMetricsResponse", self._request("GET", f"/v1/posts/{_quote(id)}/metrics", query={"refresh": refresh, "workspace": workspace}, workspace_in="query", timeout=timeout))

    def get_post_comments(
        self,
        id: str,
        *,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Read comments on a published post. ``GET /v1/posts/{id}/comments``.

        Live comments/replies from the platforms. Supported: Instagram, Facebook, Threads, X. Each comment carries the accountId and platform needed to reply. YouTube is not listed yet: its comments need a restricted Google permission (youtube.force-ssl) that is not available to every account."""
        return cast("Dict[str, Any]", self._request("GET", f"/v1/posts/{_quote(id)}/comments", query={"workspace": workspace}, workspace_in="query", timeout=timeout))

    def list_recent_comments(
        self,
        *,
        platform: Union[Literal["instagram", "facebook", "threads", "x"], NotGiven] = NOT_GIVEN,
        account_id: Union[str, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Recent comments. ``GET /v1/comments``.

        Comments on the latest 10 posts of every connected Instagram, Facebook and Threads account, including posts not published with Breakreach, plus replies to X posts published with Breakreach. Newest first. Each comment carries the accountId and platform needed to reply. YouTube is not listed yet: its comments need a restricted Google permission (youtube.force-ssl) that is not available to every account."""
        return cast("Dict[str, Any]", self._request("GET", "/v1/comments", query={"platform": platform, "accountId": account_id, "workspace": workspace}, workspace_in="query", timeout=timeout))

    def reply_to_comment(
        self,
        *,
        account_id: str,
        platform: Literal["instagram", "facebook", "threads", "x"],
        comment_id: str,
        message: str,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Reply to a comment. ``POST /v1/comments/reply``.

        Replies to a comment on a published post. Supported: Instagram, Facebook, Threads, X. YouTube is not listed yet: its comments need a restricted Google permission (youtube.force-ssl) that is not available to every account.

        Sends an Idempotency-Key (generated unless idempotency_key is given) and retries safely with it."""
        return cast("Dict[str, Any]", self._request("POST", "/v1/comments/reply", body={"accountId": account_id, "platform": platform, "commentId": comment_id, "message": message, "workspace": workspace}, idempotent=True, idempotency_key=idempotency_key, workspace_in="body", timeout=timeout))

    def get_content_performance(
        self,
        *,
        days: Union[int, NotGiven] = NOT_GIVEN,
        platform: Union[str, NotGiven] = NOT_GIVEN,
        account_id: Union[str, NotGiven] = NOT_GIVEN,
        sort_by: Union[Literal["date", "views", "likes", "comments", "shares", "engagement"], NotGiven] = NOT_GIVEN,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        refresh: Union[bool, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Content performance. ``GET /v1/performance``.

        Per-post views, likes, comments, shares and engagement rate over the last N days (max 365), with totals per platform. Covers all posts on connected Instagram, Facebook, Threads, X, YouTube and Bluesky accounts, including posts not made with Breakreach. Cached up to 1 hour.

        Args:
            refresh: Rebuild from the platforms instead of the cache"""
        return cast("Dict[str, Any]", self._request("GET", "/v1/performance", query={"days": days, "platform": platform, "accountId": account_id, "sortBy": sort_by, "limit": limit, "refresh": refresh, "workspace": workspace}, workspace_in="query", timeout=timeout))

    def list_conversations(
        self,
        *,
        platform: Union[Literal["facebook", "instagram", "x"], NotGiven] = NOT_GIVEN,
        account_id: Union[str, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """List direct message conversations. ``GET /v1/inbox``.

        Conversations on connected Facebook Pages (Messenger), Instagram and X accounts, newest first. Accounts whose messages can't be loaded are returned in errors with the reason."""
        return cast("Dict[str, Any]", self._request("GET", "/v1/inbox", query={"platform": platform, "accountId": account_id, "workspace": workspace}, workspace_in="query", timeout=timeout))

    def get_conversation_messages(
        self,
        conversation_id: str,
        *,
        account_id: str,
        participant_id: Union[str, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Read a conversation. ``GET /v1/inbox/{conversationId}/messages``.

        Messages of one conversation, oldest first. participantId is required for X."""
        return cast("Dict[str, Any]", self._request("GET", f"/v1/inbox/{_quote(conversation_id)}/messages", query={"accountId": account_id, "participantId": participant_id, "workspace": workspace}, workspace_in="query", timeout=timeout))

    def send_direct_message(
        self,
        conversation_id: str,
        *,
        account_id: str,
        message: str,
        participant_id: Union[str, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Send a direct message. ``POST /v1/inbox/{conversationId}/messages``.

        Replies in a conversation. Instagram and Messenger only accept replies within 24 hours of the person's last message. participantId is required for X.

        Sends an Idempotency-Key (generated unless idempotency_key is given) and retries safely with it."""
        return cast("Dict[str, Any]", self._request("POST", f"/v1/inbox/{_quote(conversation_id)}/messages", body={"accountId": account_id, "message": message, "participantId": participant_id, "workspace": workspace}, idempotent=True, idempotency_key=idempotency_key, workspace_in="body", timeout=timeout))

    def list_comment_dm_rules(
        self,
        *,
        account_id: Union[str, NotGiven] = NOT_GIVEN,
        media_id: Union[str, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> ListCommentDmRulesResponse:
        """List Comment to DM rules. ``GET /v1/comment-dm-rules``.

        Comment to DM automations: when someone comments a keyword on a post of an Instagram account or a Facebook Page (or any post of it), Breakreach sends them a DM through a private reply (Instagram Direct, or Messenger from the Page), and optionally a public reply under the comment. Both networks allow one private reply per comment within 7 days of it, and Breakreach sends each person one DM per rule."""
        return cast("ListCommentDmRulesResponse", self._request("GET", "/v1/comment-dm-rules", query={"accountId": account_id, "mediaId": media_id, "workspace": workspace}, workspace_in="query", timeout=timeout))

    def create_comment_dm_rule(
        self,
        *,
        account_id: Union[str, NotGiven] = NOT_GIVEN,
        media_id: Union[Optional[str], NotGiven] = NOT_GIVEN,
        post_id: Union[str, NotGiven] = NOT_GIVEN,
        keywords: Union[List[str], NotGiven] = NOT_GIVEN,
        match: Union[Literal["contains", "exact"], NotGiven] = NOT_GIVEN,
        dm_text: Union[str, NotGiven] = NOT_GIVEN,
        public_replies: Union[List[str], NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        idempotency_key: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> CreateCommentDmRuleResponse:
        """Create a Comment to DM rule. ``POST /v1/comment-dm-rules``.

        Starts watching the comments of the account (Breakreach subscribes it to Instagram's comment webhooks, or the Page's feed webhooks). Requires an active plan or trial on the workspace.

        Sends an Idempotency-Key (generated unless idempotency_key is given) and retries safely with it.

        Args:
            account_id: Instagram account or Facebook Page id from /v1/accounts (create only, a rule can't change account)
            media_id: Instagram or Facebook post id to watch (from /v1/comment-dm-rules/media or the postId of /v1/comments). Omit or null for every post
            post_id: Instead of mediaId: a Breakreach post id published on this account
            keywords: Words or phrases that trigger the DM, case and accents ignored. Empty = every comment
            match: contains = the keyword appears as a whole word or phrase; exact = the comment is just the keyword (punctuation and emoji around it ignored)
            dm_text: The DM sent to the commenter, links allowed. {username} becomes their @handle on Instagram, their first name on Facebook. Required on create
            public_replies: Optional public replies under the comment once the DM is sent, one picked at random. {username} becomes their @handle on Instagram, their first name on Facebook"""
        return cast("CreateCommentDmRuleResponse", self._request("POST", "/v1/comment-dm-rules", body={"accountId": account_id, "mediaId": media_id, "postId": post_id, "keywords": keywords, "match": match, "dmText": dm_text, "publicReplies": public_replies, "active": active, "workspace": workspace}, idempotent=True, idempotency_key=idempotency_key, workspace_in="body", timeout=timeout))

    def list_comment_dm_media(
        self,
        *,
        account_id: str,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Latest posts of an Instagram account or a Facebook Page. ``GET /v1/comment-dm-rules/media``.

        The account's latest posts with their ids, to pick the mediaId of a rule."""
        return cast("Dict[str, Any]", self._request("GET", "/v1/comment-dm-rules/media", query={"accountId": account_id, "limit": limit, "workspace": workspace}, workspace_in="query", timeout=timeout))

    def update_comment_dm_rule(
        self,
        id: str,
        *,
        account_id: Union[str, NotGiven] = NOT_GIVEN,
        media_id: Union[Optional[str], NotGiven] = NOT_GIVEN,
        post_id: Union[str, NotGiven] = NOT_GIVEN,
        keywords: Union[List[str], NotGiven] = NOT_GIVEN,
        match: Union[Literal["contains", "exact"], NotGiven] = NOT_GIVEN,
        dm_text: Union[str, NotGiven] = NOT_GIVEN,
        public_replies: Union[List[str], NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> UpdateCommentDmRuleResponse:
        """Update a Comment to DM rule. ``PATCH /v1/comment-dm-rules/{id}``.

        Only the fields given change. active false pauses the rule; mediaId null makes it watch every post.

        Args:
            account_id: Instagram account or Facebook Page id from /v1/accounts (create only, a rule can't change account)
            media_id: Instagram or Facebook post id to watch (from /v1/comment-dm-rules/media or the postId of /v1/comments). Omit or null for every post
            post_id: Instead of mediaId: a Breakreach post id published on this account
            keywords: Words or phrases that trigger the DM, case and accents ignored. Empty = every comment
            match: contains = the keyword appears as a whole word or phrase; exact = the comment is just the keyword (punctuation and emoji around it ignored)
            dm_text: The DM sent to the commenter, links allowed. {username} becomes their @handle on Instagram, their first name on Facebook. Required on create
            public_replies: Optional public replies under the comment once the DM is sent, one picked at random. {username} becomes their @handle on Instagram, their first name on Facebook"""
        return cast("UpdateCommentDmRuleResponse", self._request("PATCH", f"/v1/comment-dm-rules/{_quote(id)}", body={"accountId": account_id, "mediaId": media_id, "postId": post_id, "keywords": keywords, "match": match, "dmText": dm_text, "publicReplies": public_replies, "active": active, "workspace": workspace}, workspace_in="body", timeout=timeout))

    def delete_comment_dm_rule(
        self,
        id: str,
        *,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Delete a Comment to DM rule. ``DELETE /v1/comment-dm-rules/{id}``.

        Deletes the rule with its activity."""
        return cast("Dict[str, Any]", self._request("DELETE", f"/v1/comment-dm-rules/{_quote(id)}", query={"workspace": workspace}, workspace_in="query", timeout=timeout))

    def list_comment_dm_events(
        self,
        id: str,
        *,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> ListCommentDmEventsResponse:
        """Activity of a Comment to DM rule. ``GET /v1/comment-dm-rules/{id}/events``.

        Comments that matched the rule, newest first, kept 90 days: sent, failed (with the reason) or skipped. The same outcomes are pushed to webhooks subscribed to comment_dm.sent and comment_dm.failed."""
        return cast("ListCommentDmEventsResponse", self._request("GET", f"/v1/comment-dm-rules/{_quote(id)}/events", query={"limit": limit, "workspace": workspace}, workspace_in="query", timeout=timeout))

    def list_dm_automations(
        self,
        *,
        account_id: Union[str, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> ListDmAutomationsResponse:
        """List DM automations. ``GET /v1/dm-automations``.

        DM automations: when someone DMs a keyword, mentions the account in their story, replies to a story or opens a ref link, Breakreach answers in Instagram Direct (or Messenger for a Facebook Page) and walks a flow of messages, waits, conditions and handoffs for that person. Replies only go out within Meta's 24-hour window after the person's last message; a person is in one flow at a time, and someone answering by hand stops it."""
        return cast("ListDmAutomationsResponse", self._request("GET", "/v1/dm-automations", query={"accountId": account_id, "workspace": workspace}, workspace_in="query", timeout=timeout))

    def create_dm_automation(
        self,
        *,
        account_id: Union[str, NotGiven] = NOT_GIVEN,
        name: Union[str, NotGiven] = NOT_GIVEN,
        trigger: Union[DmTrigger, NotGiven] = NOT_GIVEN,
        steps: Union[List[DmStep], NotGiven] = NOT_GIVEN,
        reentry: Union[Literal["once", "always"], NotGiven] = NOT_GIVEN,
        cooldown_hours: Union[int, NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> CreateDmAutomationResponse:
        """Create a DM automation. ``POST /v1/dm-automations``.

        Subscribes the account to Meta's message webhooks and starts answering. Requires an active plan or trial on the workspace.

        Args:
            account_id: Instagram account or Facebook Page id from /v1/accounts (create only)
            steps: Required on create. On update, the whole list
            reentry: once = a person goes through it once; always = each time they trigger it, at most once per cooldownHours"""
        return cast("CreateDmAutomationResponse", self._request("POST", "/v1/dm-automations", body={"accountId": account_id, "name": name, "trigger": trigger, "steps": steps, "reentry": reentry, "cooldownHours": cooldown_hours, "active": active, "workspace": workspace}, workspace_in="body", timeout=timeout))

    def update_dm_automation(
        self,
        id: str,
        *,
        account_id: Union[str, NotGiven] = NOT_GIVEN,
        name: Union[str, NotGiven] = NOT_GIVEN,
        trigger: Union[DmTrigger, NotGiven] = NOT_GIVEN,
        steps: Union[List[DmStep], NotGiven] = NOT_GIVEN,
        reentry: Union[Literal["once", "always"], NotGiven] = NOT_GIVEN,
        cooldown_hours: Union[int, NotGiven] = NOT_GIVEN,
        active: Union[bool, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> UpdateDmAutomationResponse:
        """Update a DM automation. ``PATCH /v1/dm-automations/{id}``.

        Only the fields given change; steps replaces the whole flow (keep the ids of unchanged steps so people in the flow carry on). active false pauses it and stops the people in it.

        Args:
            account_id: Instagram account or Facebook Page id from /v1/accounts (create only)
            steps: Required on create. On update, the whole list
            reentry: once = a person goes through it once; always = each time they trigger it, at most once per cooldownHours"""
        return cast("UpdateDmAutomationResponse", self._request("PATCH", f"/v1/dm-automations/{_quote(id)}", body={"accountId": account_id, "name": name, "trigger": trigger, "steps": steps, "reentry": reentry, "cooldownHours": cooldown_hours, "active": active, "workspace": workspace}, workspace_in="body", timeout=timeout))

    def delete_dm_automation(
        self,
        id: str,
        *,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> Dict[str, Any]:
        """Delete a DM automation. ``DELETE /v1/dm-automations/{id}``.

        Deletes the automation with its runs; people in the flow stop."""
        return cast("Dict[str, Any]", self._request("DELETE", f"/v1/dm-automations/{_quote(id)}", query={"workspace": workspace}, workspace_in="query", timeout=timeout))

    def list_dm_automation_runs(
        self,
        id: str,
        *,
        limit: Union[int, NotGiven] = NOT_GIVEN,
        workspace: Union[str, NotGiven] = NOT_GIVEN,
        timeout: Optional[float] = None,
    ) -> ListDmAutomationRunsResponse:
        """Runs of a DM automation. ``GET /v1/dm-automations/{id}/runs``.

        Each person who went through it, newest first, kept 90 days: every step sent, choices tapped, clicks, and how it ended. Webhooks subscribed to dm_automation.started, dm_automation.handoff, dm_automation.finished and dm_automation.failed get the same events as they happen."""
        return cast("ListDmAutomationRunsResponse", self._request("GET", f"/v1/dm-automations/{_quote(id)}/runs", query={"limit": limit, "workspace": workspace}, workspace_in="query", timeout=timeout))
